# Install mongo DB in VM3

- name: install mongo
  hosts: vm3
  become: yes
  become_method: sudo
  module_defaults:
    apt:
      force_apt_get: yes
  roles:
    - mongodb


# Install system apt packages
- hosts: vm1
  become: yes
  become_method: sudo
  roles:
    - nodejs