name: Ansible deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
#### 
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
####
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests
#####
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2.3.0
      with:
        playbook: playbook.yml
        directory: ./ansible
        key: ${{secrets.SSH_KEY}}
        inventory: |
          [vm1]
          20.55.59.93
          [group1]
          example.com
        vault_password: ${{secrets.VAULT_PASSWORD}}
        options: |
          --limit group1
          --extra-vars hello=there
          --verbose

