name: Ansible deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    #### 
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
####
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.9.2 requests

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/jojokey.pem
        chmod 400 ~/.ssh/jojokey.pem
        cat >>~/.ssh/config <<END
        Host jojokey
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/jojokey.pem
          StrictHostKeyChecking no
          END
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}

###
#####
    - name: run exporters playbook
      run: |
        cd ansible
        ls -la
        chmod a-x hosts
        ansible-playbook -i hosts --key-file ~/.ssh/jojokey.pem playblook.yml

