name: Ansible deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
#### 
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
####
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user ansible
        python -m pip install --user paramiko
        pip install ansible requests

####
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        echo "$SSH_KEY" > ~/.ssh/jojokey.pem
        chmod 400 ~/.ssh/jojokey.pem
        cat >>~/.ssh/config <<END
        Host jojokey
          HostName $SSH_HOST
          User jojoadmin
          IdentityFile ~/.ssh/jojokey.pem
          StrictHostKeyChecking no
          END
      env:
        SSH_KEY: ${{secrets.SSH_KEY}}

    - name: run exporters playbook
      run: |
        ls -la 
        ansible-playbook playblook.yml -i hosts --key-file ~/.ssh/id_rsa
        ansible-playbook ansible/playblook.yml -i hosts --key-file ~/.ssh/jojokey.pem
#####
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2.3.0
      with:
        playbook: playbook.yml
        directory: ./ansible
        key: ${{secrets.SSH_KEY}}
        #inventory:
        #vault_password: ${{secrets.VAULT_PASSWORD}}
        options: |
          --limit vm1
          --extra-vars hello=there
          --verbose
          -i hosts